services:
  - type: web
    name: my-app-name # the name of this service, you should change this
    runtime: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # we already created these two files for you
    preDeployCommand: "bin/rails db:migrate"
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: WEB_CONCURRENCY
        value: 1
      - key: RAILS_MAX_THREADS
        value: 3
  - type: worker
    name: my-app-name-worker
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bin/jobs --mode async"
    envVars:
      - key: DATABASE_URL
        sync: false
